// 袴カタログの商品データ
// colors は複数指定可能（例: ["ブルー", "スカイブルー"]）。チップで選択した色のいずれかを含む商品が表示されます。
const HAKAMA_ITEMS = [
  {
    id: 1,
    name: "H-2305",
    price: 82500,
    memberPrice: 57750,
    colors: ["グレー", "ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_2305.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 2,
    name: "H-2501",
    price: 77000,
    memberPrice: 53900,
    colors: ["ブラック", "グレー"],
    pattern: "",
    image: "images/H_2501.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 3,
    name: "H-2201",
    price: 66000,
    memberPrice: 46200,
    colors: ["ホワイト", "ブラウン"],
    pattern: "",
    image: "images/H_2201.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 4,
    name: "H-2303",
    price: 82500,
    memberPrice: 57750,
    colors: ["ブラウン", "イエロー"],
    pattern: "",
    image: "images/H_2303.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 5,
    name: "AN-5",
    price: 77000,
    memberPrice: 53900,
    colors: ["ピンク", "ホワイト"],
    pattern: "",
    image: "images/AN_5.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 6,
    name: "AN-6",
    price: 77000,
    memberPrice: 53900,
    colors: ["グリーン", "ブラック"],
    pattern: "",
    image: "images/AN_6.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 7,
    name: "H-1301",
    price: 77000,
    memberPrice: 53900,
    colors: ["ホワイト"],
    pattern: "",
    image: "images/H_1301.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 8,
    name: "H-1304",
    price: 77000,
    memberPrice: 53900,
    colors: ["レッド", "ブラウン"],
    pattern: "",
    image: "images/H_1304.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 9,
    name: "H-1305",
    price: 77000,
    memberPrice: 53900,
    colors: ["レッド", "ホワイト", "ブラック"],
    pattern: "",
    image: "images/H_1305.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 10,
    name: "H-1306",
    price: 77000,
    memberPrice: 53900,
    colors: ["パープル"],
    pattern: "",
    image: "images/H_1306.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 11,
    name: "H-1501",
    price: 77000,
    memberPrice: 53900,
    colors: ["ホワイト", "レッド"],
    pattern: "",
    image: "images/H_1501.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 12,
    name: "H-1601",
    price: 77000,
    memberPrice: 53900,
    colors: ["パープル", "ブラウン"],
    pattern: "",
    image: "images/H_1601.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 13,
    name: "H-1801",
    price: 77000,
    memberPrice: 53900,
    colors: ["グリーン", "レッド", "オレンジ"],
    pattern: "",
    image: "images/H_1801.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 14,
    name: "H-2001",
    price: 77000,
    memberPrice: 53900,
    colors: ["グリーン", "ブルー"],
    pattern: "",
    image: "images/H_2001.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 15,
    name: "H-201",
    price: 33000,
    memberPrice: 23100,
    colors: ["レッド"],
    pattern: "",
    image: "images/H_201.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 16,
    name: "H-2101",
    price: 66000,
    memberPrice: 46200,
    colors: ["ブラック", "イエロー"],
    pattern: "",
    image: "images/H_2101.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 17,
    name: "H-2102",
    price: 66000,
    memberPrice: 46200,
    colors: ["ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_2102.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 18,
    name: "H-211",
    price: 33000,
    memberPrice: 23100,
    colors: ["グリーン"],
    pattern: "",
    image: "images/H_211.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 19,
    name: "H-212",
    price: 33000,
    memberPrice: 23100,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_212.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 20,
    name: "H-213",
    price: 33000,
    memberPrice: 23100,
    colors: ["ピンク"],
    pattern: "",
    image: "images/H_213.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 21,
    name: "H-219",
    price: 33000,
    memberPrice: 23100,
    colors: ["ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_219.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 22,
    name: "H-220",
    price: 33000,
    memberPrice: 23100,
    colors: ["パープル", "ライトパープル"],
    pattern: "",
    image: "images/H_220.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 23,
    name: "H-2202",
    price: 66000,
    memberPrice: 46200,
    colors: ["ホワイト", "グレー", "ピンク"],
    pattern: "",
    image: "images/H_2202.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 24,
    name: "H-2203",
    price: 66000,
    memberPrice: 46200,
    colors: ["ホワイト", "グレー", "ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_2203.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 25,
    name: "H-223",
    price: 33000,
    memberPrice: 23100,
    colors: ["ホワイト", "クリーム"],
    pattern: "",
    image: "images/H_223.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 26,
    name: "H-225",
    price: 33000,
    memberPrice: 23100,
    colors: ["ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_225.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 27,
    name: "H-2301",
    price: 77000,
    memberPrice: 53900,
    colors: ["ホワイト", "グレー"],
    pattern: "",
    image: "images/H_2301.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 28,
    name: "H-2302",
    price: 82500,
    memberPrice: 57750,
    colors: ["ホワイト"],
    pattern: "",
    image: "images/H_2302.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 29,
    name: "H-2304",
    price: 82500,
    memberPrice: 57750,
    colors: ["ブラウン", "ホワイト", "レッド"],
    pattern: "",
    image: "images/H_2304.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 30,
    name: "H-231",
    price: 33000,
    memberPrice: 23100,
    colors: ["ブルー", "スカイブルー"],
    pattern: "",
    image: "images/H_231.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 31,
    name: "H-2502",
    price: 77000,
    memberPrice: 53900,
    colors: ["ブラック", "パープル", "ライトパープル"],
    pattern: "",
    image: "images/H_2502.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 32,
    name: "H-301",
    price: 33000,
    memberPrice: 23100,
    colors: ["イエロー"],
    pattern: "",
    image: "images/H_301.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 33,
    name: "H-302",
    price: 55000,
    memberPrice: 38500,
    colors: ["ホワイト", "パープル"],
    pattern: "",
    image: "images/H_302.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 34,
    name: "H-401",
    price: 44000,
    memberPrice: 30800,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_401.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 35,
    name: "H-402",
    price: 55000,
    memberPrice: 38500,
    colors: ["パープル", "レッド"],
    pattern: "",
    image: "images/H_402.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 36,
    name: "H-403",
    price: 33000,
    memberPrice: 23100,
    colors: ["ピンク"],
    pattern: "",
    image: "images/H_403.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 37,
    name: "H-501",
    price: 55000,
    memberPrice: 38500,
    colors: ["ホワイト", "ピンク"],
    pattern: "",
    image: "images/H_501.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 38,
    name: "H-502",
    price: 55000,
    memberPrice: 38500,
    colors: ["ブラック", "レッド"],
    pattern: "",
    image: "images/H_502.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 39,
    name: "H-503",
    price: 44000,
    memberPrice: 30800,
    colors: ["ホワイト"],
    pattern: "",
    image: "images/H_503.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 40,
    name: "H-506",
    price: 55000,
    memberPrice: 38500,
    colors: ["ピンク"],
    pattern: "",
    image: "images/H_506.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 41,
    name: "H-507",
    price: 55000,
    memberPrice: 38500,
    colors: ["ピンク", "ライトパープル"],
    pattern: "",
    image: "images/H_507.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 42,
    name: "H-508",
    price: 55000,
    memberPrice: 38500,
    colors: ["ピンク"],
    pattern: "",
    image: "images/H_508.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 43,
    name: "H-702",
    price: 55000,
    memberPrice: 38500,
    colors: ["ライトパープル"],
    pattern: "",
    image: "images/H_702.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 44,
    name: "H-703",
    price: 44000,
    memberPrice: 30800,
    colors: ["レッド"],
    pattern: "",
    image: "images/H_703.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 45,
    name: "H-705",
    price: 55000,
    memberPrice: 38500,
    colors: ["ホワイト", "ピンク"],
    pattern: "",
    image: "images/H_705.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 46,
    name: "H-706",
    price: 44000,
    memberPrice: 30800,
    colors: ["オレンジ", "ブラウン"],
    pattern: "",
    image: "images/H_706.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 47,
    name: "H-707",
    price: 44000,
    memberPrice: 30800,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_707.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 48,
    name: "H-708",
    price: 55000,
    memberPrice: 38500,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_708.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 49,
    name: "H-709",
    price: 55000,
    memberPrice: 38500,
    colors: ["パープル"],
    pattern: "",
    image: "images/H_709.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 50,
    name: "H-710",
    price: 55000,
    memberPrice: 38500,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_710.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 51,
    name: "H-903",
    price: 55000,
    memberPrice: 38500,
    colors: ["ホワイト", "ピンク", "レッド"],
    pattern: "",
    image: "images/H_903.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 52,
    name: "H-905",
    price: 55000,
    memberPrice: 38500,
    colors: ["ホワイト"],
    pattern: "",
    image: "images/H_905.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 53,
    name: "H-906",
    price: 55000,
    memberPrice: 38500,
    colors: ["ブラック"],
    pattern: "",
    image: "images/H_906.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 54,
    name: "MY-1",
    price: 33000,
    memberPrice: 23100,
    colors: ["レッド"],
    pattern: "",
    image: "images/MY_1.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 55,
    name: "MY-2",
    price: 33000,
    memberPrice: 23100,
    colors: ["イエロー"],
    pattern: "",
    image: "images/MY_2.JPG",
    tags: [],
    description: "準備中"
  },
  {
    id: 56,
    name: "MY-3",
    price: 33000,
    memberPrice: 23100,
    colors: ["グリーン"],
    pattern: "",
    image: "images/MY_3.jpg",
    tags: [],
    description: "準備中"
  },
  {
    id: 57,
    name: "MY-4",
    price: 33000,
    memberPrice: 23100,
    colors: ["ピンク"],
    pattern: "",
    image: "images/MY_4.jpg",
    tags: [],
    description: "準備中"
  },
];
